import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthRouteGuard, RecoilRootProvider } from "@/app/components";
import { Navbar } from "@/shared";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <RecoilRootProvider>
          <AuthRouteGuard>
            <main className="min-h-screen">
              <ToastContainer
                position="top-center"
                autoClose={2000}
                hideProgressBar={true}
                closeOnClick={true}
                theme="light"
              />
              <Navbar />
              <section className="h-[calc(100vh-50px)] sm:h-[calc(100vh-40px)]">
                {children}
              </section>
            </main>
          </AuthRouteGuard>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
