import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { RoutePublicGuard, RecoilRootProvider } from "@/app/components";
import { Navbar } from "@/shared";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <RecoilRootProvider>
          <RoutePublicGuard>
            <main className="min-h-screen">
              <Navbar />
              {children}
            </main>
          </RoutePublicGuard>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
